name: blastxml_to_top_descr
owner: peterjc
homepage_url: https://github.com/peterjc/galaxy_blast/tree/master/tools/blastxml_to_top_descr
remote_repository_url: https://github.com/peterjc/galaxy_blast/tree/master/tools/blastxml_to_top_descr
description: Make table of top BLAST match descriptions
long_description: |
  NCBI BLAST+ (and the older NCBI "legacy" BLAST) can output in a range of formats
  including text, tabular and a more detailed XML format. You can do a lot of things
  with tabular files in Galaxy (sorting, filtering, joins, etc), however until BLAST+
  2.2.28 the tabular output never included the hit descriptions (titles) found in
  the other output formats.

  This tool turns a BLAST XML file into a simple tabular file containing one row per
  query sequence, containing the query identifier and then the three (by default)
  top hit descriptions (i.e. the first three). If a query doesn''t have that many
  hits, then these entries are left blank.

  This tool can also be used with the tabular output from BLAST+ instead, provided
  the relevant columns are provided. The default settings will work with the default
  25 column extended output from the BLAST+ tools wrapped in Galaxy. Note if a query
  has no hits, it does not appear in the BLAST tabular output.
categories:
- Convert Formats
- Sequence Analysis
- Text Manipulation
type: unrestricted
include:
- strip_components: 2
  source:
  - ../../test-data/blastp_four_human_vs_rhodopsin.xml
  - ../../test-data/blastp_four_human_vs_rhodopsin_converted_ext.tabular
  - ../../test-data/blastp_four_human_vs_rhodopsin_top3.tabular
  - ../../test-data/blastp_four_human_vs_rhodopsin_top3_positive.tabular
  - ../../tools/blastxml_to_top_descr/README.rst
  - ../../tools/blastxml_to_top_descr/blastxml_to_top_descr.py
  - ../../tools/blastxml_to_top_descr/blastxml_to_top_descr.xml
  - ../../tools/blastxml_to_top_descr/repository_dependencies.xml
