name: blast_rbh
owner: peterjc
homepage_url: https://github.com/peterjc/galaxy_blast/tree/master/tools/blast_rbh
remote_repository_url: https://github.com/peterjc/galaxy_blast/tree/master/tools/blast_rbh
description: BLAST Reciprocal Best Hits (RBH) from two FASTA files
long_description: |
  Builds BLAST databases and runs reciprocal searches, filters them,
  and then identifies and reports any reciprocal best hits (RBH).
categories:
- Fasta Manipulation
- Sequence Analysis
type: unrestricted
include:
- strip_components: 2
  source:
  - ../../test-data/four_human_proteins.fasta
  - ../../test-data/k12_edited_proteins.fasta
  - ../../test-data/k12_ten_proteins.fasta
  - ../../test-data/rbh_blastn_three_human_mRNA_vs_rhodopsin_nucs.tabular
  - ../../test-data/rbh_blastp_four_human_vs_rhodopsin_proteins.tabular
  - ../../test-data/rbh_blastp_k12.tabular
  - ../../test-data/rbh_blastp_k12_self.tabular
  - ../../test-data/rbh_megablast_rhodopsin_nucs_vs_three_human_mRNA.tabular
  - ../../test-data/rbh_none.tabular
  - ../../test-data/rbh_tblastx_rhodopsin_nucs_vs_three_human_mRNA.tabular
  - ../../test-data/rhodopsin_nucs.fasta
  - ../../test-data/rhodopsin_proteins.fasta
  - ../../test-data/three_human_mRNA.fasta
  - ../../tools/blast_rbh/README.rst
  - ../../tools/blast_rbh/best_hits.py
  - ../../tools/blast_rbh/blast_rbh.py
  - ../../tools/blast_rbh/blast_rbh.xml
