name: ncbi_blast_plus
owner: devteam
homepage_url: https://blast.ncbi.nlm.nih.gov/
remote_repository_url: https://github.com/peterjc/galaxy_blast/tree/master/tools/ncbi_blast_plus
description: NCBI BLAST+
long_description: |
  The NCBI BLAST+ tools find regions of similarity between biological sequences.
  The programs compare nucleotide or protein sequences to sequence databases and
  calculate the statistical significance.
categories:
- Sequence Analysis
type: unrestricted
include:
- strip_components: 0
  source:
  - test-data/blastdb.loc
  - test-data/blastdb_d.loc
  - test-data/blastdb_p.loc
  - test-data/blastn_arabidopsis.extended.tabular
  - test-data/blastn_arabidopsis.standard.tabular
  - test-data/blastn_arabidopsis.xml
  - test-data/blastn_chimera_vs_three_human_max1.tabular
  - test-data/blastn_chimera_vs_three_human_max1.txt
  - test-data/blastn_rhodopsin_vs_three_human.columns.tabular
  - test-data/blastn_rhodopsin_vs_three_human.tabular
  - test-data/blastn_rhodopsin_vs_three_human.xml
  - test-data/blastn_rhodopsin_vs_three_human_converted.tabular
  - test-data/blastn_chimera_vs_three_human_db.tabular
  - test-data/blastn_chimera_vs_rhodopsin_db.tabular
  - test-data/blastn_chimera_vs_three_human_and_rhodopsin_db.tabular
  - test-data/blastp_four_human_vs_rhodopsin.tabular
  - test-data/blastp_four_human_vs_rhodopsin.xml
  - test-data/blastp_four_human_vs_rhodopsin_converted.tabular
  - test-data/blastp_four_human_vs_rhodopsin_converted_ext.tabular
  - test-data/blastp_four_human_vs_rhodopsin_ext.tabular
  - test-data/blastp_human_vs_pdb_seg_no.xml
  - test-data/blastp_human_vs_pdb_seg_no_converted_ext.tabular
  - test-data/blastp_human_vs_pdb_seg_no_converted_std.tabular
  - test-data/blastp_rhodopsin_vs_four_human.tabular
  - test-data/blastp_sample.xml
  - test-data/blastp_sample_converted.tabular
  - test-data/blastx_rhodopsin_vs_four_human.tabular
  - test-data/blastx_rhodopsin_vs_four_human.xml
  - test-data/blastx_rhodopsin_vs_four_human_all.tabular
  - test-data/blastx_rhodopsin_vs_four_human_converted.tabular
  - test-data/blastx_rhodopsin_vs_four_human_converted_ext.tabular
  - test-data/blastx_rhodopsin_vs_four_human_ext.tabular
  - test-data/blastx_sample.xml
  - test-data/blastx_sample_converted.tabular
  - test-data/cd00003.smp
  - test-data/cd00003_and_cd00008.aux
  - test-data/cd00003_and_cd00008.freq
  - test-data/cd00003_and_cd00008.loo
  - test-data/cd00003_and_cd00008.phr
  - test-data/cd00003_and_cd00008.pin
  - test-data/cd00003_and_cd00008.psd
  - test-data/cd00003_and_cd00008.psi
  - test-data/cd00003_and_cd00008.psq
  - test-data/cd00003_and_cd00008.rps
  - test-data/cd00008.smp
  - test-data/chimera.fasta
  - test-data/chimera.fasta.gz
  - test-data/convert2blastmask_four_human_masked.maskinfo-asn1
  - test-data/convert2blastmask_four_human_masked.maskinfo-asn1-binary
  - test-data/dustmasker_three_human.fasta
  - test-data/dustmasker_three_human.maskinfo-asn1
  - test-data/dustmasker_three_human.maskinfo-asn1-binary
  - test-data/empty_file.dat
  - test-data/four_human_proteins.dbinfo.txt
  - test-data/four_human_proteins.fasta
  - test-data/four_human_proteins.fasta.log.txt
  - test-data/four_human_proteins.fasta.phd
  - test-data/four_human_proteins.fasta.phi
  - test-data/four_human_proteins.fasta.phr
  - test-data/four_human_proteins.fasta.pin
  - test-data/four_human_proteins.fasta.pog
  - test-data/four_human_proteins.fasta.psd
  - test-data/four_human_proteins.fasta.psi
  - test-data/four_human_proteins.fasta.psq
  - test-data/four_human_proteins_masked.fasta
  - test-data/four_human_proteins_taxid.fasta.log.txt
  - test-data/four_human_proteins_taxid.fasta.phd
  - test-data/four_human_proteins_taxid.fasta.phi
  - test-data/four_human_proteins_taxid.fasta.phr
  - test-data/four_human_proteins_taxid.fasta.pin
  - test-data/four_human_proteins_taxid.fasta.pog
  - test-data/four_human_proteins_taxid.fasta.psd
  - test-data/four_human_proteins_taxid.fasta.psi
  - test-data/four_human_proteins_taxid.fasta.psq
  - test-data/rhodopsin_nucs.dbinfo.txt
  - test-data/rhodopsin_nucs.fasta
  - test-data/rhodopsin_nucs.fasta.gz
  - test-data/rhodopsin_nucs.fasta.log.txt
  - test-data/rhodopsin_nucs.fasta.nhd
  - test-data/rhodopsin_nucs.fasta.nhi
  - test-data/rhodopsin_nucs.fasta.nhr
  - test-data/rhodopsin_nucs.fasta.nin
  - test-data/rhodopsin_nucs.fasta.nog
  - test-data/rhodopsin_nucs.fasta.nsd
  - test-data/rhodopsin_nucs.fasta.nsi
  - test-data/rhodopsin_nucs.fasta.nsq
  - test-data/rhodopsin_nucs.fasta.nnd
  - test-data/rhodopsin_nucs.fasta.nni
  - test-data/rhodopsin_nucs.no_gi.fasta
  - test-data/rhodopsin_nucs.blastdbcmd.txt
  - test-data/rhodopsin_bufo.fasta
  - test-data/rhodopsin_proteins.fasta
  - test-data/segmasker_four_human.fasta
  - test-data/segmasker_four_human.maskinfo-asn1
  - test-data/segmasker_four_human.maskinfo-asn1-binary
  - test-data/tblastn_four_human_vs_rhodopsin.html
  - test-data/tblastn_four_human_vs_rhodopsin.tabular
  - test-data/tblastn_four_human_vs_rhodopsin_deflines.tabular
  - test-data/tblastn_four_human_vs_rhodopsin.xml
  - test-data/tblastn_four_human_vs_rhodopsin_ext.tabular
  - test-data/tblastx_rhodopsin_vs_three_human.tabular
  - test-data/three_human_mRNA.dbinfo.txt
  - test-data/three_human_mRNA.fasta
  - test-data/three_human_mRNA.fasta.gz
  - test-data/three_human_mRNA.fasta.log.txt
  - test-data/three_human_mRNA.fasta.nhd
  - test-data/three_human_mRNA.fasta.nhi
  - test-data/three_human_mRNA.fasta.nhr
  - test-data/three_human_mRNA.fasta.nin
  - test-data/three_human_mRNA.fasta.nog
  - test-data/three_human_mRNA.fasta.nsd
  - test-data/three_human_mRNA.fasta.nsi
  - test-data/three_human_mRNA.fasta.nsq
  - test-data/tool_data_table_conf.xml.test
  - tool-data/blastdb.loc.sample
  - tool-data/blastdb_d.loc.sample
  - tool-data/blastdb_p.loc.sample
  - tool-data/tool_data_table_conf.xml.sample
  - get_species_taxids.xml
  - README.rst
  - blastxml_to_tabular.py
  - blastxml_to_tabular.xml
  - check_no_duplicates.py
  - ncbi_blastdbcmd_info.xml
  - ncbi_blastdbcmd_wrapper.xml
  - ncbi_blastn_wrapper.xml
  - ncbi_blastp_wrapper.xml
  - ncbi_blastx_wrapper.xml
  - ncbi_convert2blastmask_wrapper.xml
  - ncbi_dustmasker_wrapper.xml
  - ncbi_macros.xml
  - ncbi_makeblastdb.xml
  - ncbi_makeprofiledb.xml
  - ncbi_rpsblast_wrapper.xml
  - ncbi_rpstblastn_wrapper.xml
  - ncbi_segmasker_wrapper.xml
  - ncbi_tblastn_wrapper.xml
  - ncbi_tblastx_wrapper.xml
